Merged PR 5090: Upgrading ATS.eFP.Entities to the 1.0.2.290 in order to have ServiceLevel
Upgrading ATS.eFP.Entities to the 1.0.2.290 in order to have ServiceLevel property and avoid this exception:
The property 'ServiceLevel' does not exist on type 'ATS.eFP.Entities.Task.Task'. Make sure to only use property names that are defined by the type.
InnerException: StackTrace: at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

Related work items: #39803